//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDataEntities : DbContext
    {
        public EDataEntities()
            : base("name=EDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Talep> Talep { get; set; }
        public virtual DbSet<tblGorevYeri> tblGorevYeri { get; set; }
        public virtual DbSet<tblKisi> tblKisi { get; set; }
    }
}
