//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talep
    {
        public int ID { get; set; }
        public string talep1 { get; set; }
        public Nullable<int> kisiID { get; set; }
        public string talepbaslik { get; set; }
        public string taleptarihi { get; set; }
        public Nullable<bool> talepstatus { get; set; }
    
        public virtual tblKisi tblKisi { get; set; }
    }
}
