//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKisi()
        {
            this.Talep = new HashSet<Talep>();
        }
    
        public int ID { get; set; }
        [Display(Name ="Adý Soyadý")]
        public string adsoyad { get; set; }
        [Required]
        [Display(Name = "TC Kimlik Numarasý")]
        public string tcno { get; set; }
        
        [Display(Name = "Kurum Sicil Numarasý")]
        public string kurumsicilno { get; set; }        
        
        public Nullable<int> gorevyeri { get; set; }
        public Nullable<int> talepID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talep> Talep { get; set; }
        public virtual tblGorevYeri tblGorevYeri { get; set; }
    }
}
